
[![.github/workflows/main.yml](https://github.com/PannawatC/PannawatC/actions/workflows/main.yml/badge.svg?event=branch_protection_rule)](https://github.com/PannawatC/PannawatC/actions/workflows/main.yml)
